version: '3.8'

services:
  postgres:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_DB: bdb
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      POSTGRES_PASSWORD: neopa
      POSTGRES_USER: buser
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
